Api 24176/spike export oauth tool as a package
department-of-veterans-affairs/lighthouse-auth-utils pull request #41
Opened 2023-04-10 22:32 UTC by stevelong00

This is a branch with working code that refactors and wraps 3 of the 4 CLI tools as a node package. The 4th CLI tool is a bash script and cannot be wrapped.

An example project showing how to consume the node package has been added under the folder **npm-example**.  For now, this consists primarily of a README and some simple code that I have been using to run manual tests.  This projects expects the auth-utils to have been packaged into a zip file, so before running **npm install** on the example project be sure to do this packaging.  Packaging can be accomplished by running **npm run build && npm run deploy** in the root of the repo.

2023-04-19 21:37 UTC, mheusgit commented on auth-cc-script.js
> +
A comment about how this is used would be nice

2023-04-19 21:39 UTC, mheusgit commented on auth-script.js
> +
A comment how this is different than auth-cc-script.js would be helpful

2023-04-20 17:42 UTC, crolarlibertyva requested changes
Are the script renames necessary? These will break regression tests that we have in place for oauth-proxy as well as some of our monitoring bots.

2023-04-21 21:02 UTC, christineyost commented
Hi @crolarlibertyva this is a draft PR to show the types of changes we plan to make to be able to import these utilities as a module into Docserver. We will not be merging these changes in as they are, and we will not change the name of existing files in our final changes. We don't want to break any consumers of this tool! The file names we intend to use are detailed in the top comment

2023-08-04 19:02 UTC, dbrown-va commented
Closing as out of date in favor of the changes in https://github.com/department-of-veterans-affairs/lighthouse-auth-utils/pull/57

2023-08-04 19:02 UTC, closed without merging