API-25817 CCG OAuth Private Key Token Support
department-of-veterans-affairs/lighthouse-auth-utils pull request #43
Opened 2023-04-19 16:33 UTC by dmekala-va

This PR adds add support for using the private key assertion to actually request a token to the auth-cc.js in addition to the client-id/client-secret functionality that already exists. 

Link to JIRA: https://vajira.max.gov/browse/API-25817

2023-04-19 16:35 UTC, dmekala-va commented
Below shows the request to getting an access token using a private_key is successful:
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/128190370/233141712-c0c339a6-05f7-4031-a2df-18c7060b00e3.png">

2023-04-20 20:33 UTC, dbrown-va commented on auth-cc.js
> +      if (!argv.clientId || !argv.clientSecret || !argv.audience) {
With the `argv.clientSecret` confirmed present in the outer `if`, the middle `||` clause can be removed.

2023-04-20 20:34 UTC, dbrown-va commented on auth-cc.js
> +      if (!argv.clientId || !argv.key || !argv.audience) {
With the `argv.key` confirmed present in the outer `if`, the middle `||` clause can be removed.

2023-04-20 20:34 UTC, dbrown-va requested changes
Confirmed functionality, just 2 small changes requested.

2023-04-20 20:59 UTC, dbrown-va approved these changes

2023-04-21 01:42 UTC, merged