[API-26892] Refactoring auth.js
department-of-veterans-affairs/lighthouse-auth-utils pull request #53
Opened 2023-06-01 18:57 UTC by jeremyhwu

* Moved auth code logic out to auth-service
* Created auth-lib for getting tokens without using the CLI interface

2023-06-02 19:23 UTC, christineyost commented on auth-service.js
> +}
```suggestion
async function getError(message, detail, page) {
  let screenshot;

  if (page) {
    screenshot = `${args["dir"]}/lighthouse-auth-utils-${iso8601()}.png`;
    await page.screenshot({ path: screenshot, fullPage: true });
  }

  return {
      error: message,
      detail: detail,
      lastRequest: lastRequest.url(),
      screenshot: screenshot,
    };
}
```

2023-06-02 19:23 UTC, christineyost commented on auth-service.js
> +      );
```suggestion
      return getError(
        getUrlParam(interceptedRequest.url(), "error"),
        getUrlParam(interceptedRequest.url(), "error_description")
      );
```

2023-06-02 19:23 UTC, christineyost commented on auth-service.js
> +     * also likely that the JSON contains a meaningful error. report it and exit(1).
```suggestion
     * also likely that the JSON contains a meaningful error. report it.
```

2023-06-02 19:23 UTC, christineyost commented on auth-service.js
> +      exit(json.error, json.error_description);
```suggestion
      return getError(json.error, json.error_description);
```

2023-06-02 19:23 UTC, christineyost commented on auth-service.js
> +    await exit(lastDebugMessage, error, page);
```suggestion
    return getError(lastDebugMessage, error, page);
```

2023-06-02 19:23 UTC, christineyost commented on auth-service.js
> +}
In `auth.js` we can look for the `error` key in the returned json object. If it's there we can `console.log(JSON.stringify(...))` and `process.exit(1)`.

In `auth-lib.js` we can look for the same  `error` key in the returned json object. If it's there we can `throw new Error('Fetching access token failed.' , { cause: JSON.stringify(...) });`

2023-06-02 19:23 UTC, christineyost commented on auth-lib.js
> +function getAuthCode(email, password, clientId, options = defaultOptions) {
```suggestion
function getAuthCode(email, password, clientId, options) {
```

2023-06-02 19:23 UTC, christineyost commented on auth-lib.js
> +    ...options,
```suggestion
    {...defaultOptions, ...options},
```

2023-06-22 23:47 UTC, christineyost commented on auth.js
> +    console.log(response);
```suggestion
    console.log(JSON.stringify(response));
```

2023-06-22 23:47 UTC, christineyost commented on auth-service.js
> +  return await getAuthCode()
```suggestion
  return getAuthCode()
```

I think this await is unneeded

2023-06-26 16:49 UTC, christineyost commented on auth-service.js
> +      return await getError(json.error, json.error_description);
Is await needed here?

2023-06-26 20:49 UTC, christineyost commented on auth-lib.js
> +  return authCode;
Currently in some circumstances an error is being returned from auth-service.js, but that error is getting returned like a normal response object. auth-lib.js needs to check if the response is an error response, and if it is an error should be thrown

```suggestion
  const response = await authService.main(args);
  
  if (response.error) {
    throw new Error(response.detail);
  }
  
  return response;
```

2023-06-26 23:34 UTC, christineyost commented on test.js
> +    "<client-secret>"
The inputs need to be in this order to match the expected order in the getAuthCode function

```suggestion
    "<client-id>",
    "<client-secret>",
    "<email>",
    "<password>"
```

2023-06-27 16:57 UTC, christineyost commented on auth-service.js
> +
This script seems to not exit because Puppeteer keeps running because `browser.close()` is never called. This isn't a problem for the CLI because `process.exit()` is called. But that seems to be why the lib function keeps running if `process.exit()` is not called

```suggestion

  browser.close()

```

2023-06-27 16:57 UTC, christineyost commented on auth-service.js
> +      );
`browser.close()` will also need to be called anytime an error is returned

```suggestion
      const error = getError(
        getUrlParam(interceptedRequest.url(), "error"),
        getUrlParam(interceptedRequest.url(), "error_description")
      );
      browser.close();
      return error;
```

2023-06-27 16:57 UTC, christineyost commented on auth-service.js
> +      return getError(json.error, json.error_description);
```suggestion
      const error = getError(json.error, json.error_description);
      browser.close();
      return error;
```

2023-06-27 16:57 UTC, christineyost commented on auth-service.js
> +    return getError(lastDebugMessage, error, page);
```suggestion
    const error = getError(lastDebugMessage, error, page);
    browser.close();
    return error;
```

2023-06-27 16:58 UTC, christineyost commented on test.js
> +    process.exit(0);
```suggestion
```

2023-06-27 16:58 UTC, christineyost commented on test.js
> +    process.exit(1);
```suggestion
```

2023-07-06 01:11 UTC, christineyost commented on auth-service.js
> +
This `browser.close()` is still missing. It also needs to be called when the function exits successfully

2023-07-10 19:06 UTC, christineyost commented on auth-service.js
> +  browser.close()
```suggestion
  browser.close();
```

2023-07-12 00:53 UTC, stevelong00 reviewed
I noticed a linter warning when viewing this code in my IDE

2023-07-12 00:53 UTC, stevelong00 commented on auth-service.js
> +    return JSON.parse(document.querySelector("body").innerText);
ESLint indicates that the document variable is not defined

2023-07-12 16:51 UTC, jeremyhwu commented on auth-service.js
> +    return JSON.parse(document.querySelector("body").innerText);
`document` isn't a node.js variable so I believe that's why ESLint saying it is not defined. However, `page.evaluate` is a puppeteer function that returns the DOM element and allows access to client side variables. So in this context, `document` will always exist.

2023-07-12 19:33 UTC, stevelong00 commented on auth-service.js
> +    return JSON.parse(document.querySelector("body").innerText);
Makes sense, looks like a false alarm.

2023-07-12 21:32 UTC, stevelong00 reviewed
I've been using this branch with other work to test it out a bit, and I noticed a difference in failure modes.  With the following command, which incorrectly uses unicode directional quotation marks after the scope flag (thanks to slack):
```
node auth.js \
	--client-id=$LOAST_CLIENT_ID \
	--client-secret=$LOAST_SECRET \
	--user-email=va.api.user+idme.119@gmail.com \
	--user-password=Password1234! \
	--scope=“launch/patient patient/AllergyIntolerance.read” | jq
```
On the master branch it returns the following error:
```
{
  "error": "invalid_scope",
  "detail": "One or more scopes are not configured for the authorization server resource.",
  "lastRequest": "https://sandbox-api.va.gov/oauth2/redirect?state=ad51c7ec-485b-49d9-a9f5-77d90554d69b&error=invalid_scope&error_description=One+or+more+scopes+are+not+con
figured+for+the+authorization+server+resource."
}
```
On this branch it looks like there's an unhandled exception:
```
/mnt/c/All/Code/lighthouse-auth-utils/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:317
            return Promise.reject(new Error(`Protocol error (${method}): Session closed. Most likely the ${__classPrivateFieldGet(this, _CDPSessionImpl_targetType, "f")} ha
s been closed.`));
                                  ^

Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (/mnt/c/All/Code/lighthouse-auth-utils/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:317:35)
    at CDPPage._CDPPage_screenshotTask (/mnt/c/All/Code/lighthouse-auth-utils/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1016:62)
    at /mnt/c/All/Code/lighthouse-auth-utils/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:721:99
```
To reproduce, the LOAST client ID and secret will need to be added to the command.

2023-08-23 21:44 UTC, dsteeve commented
the test.js file can be used to test the code as if a function was being called instead of the CLI entrypoint. It should/will be removed before merging.

2023-08-24 12:48 UTC, crolarlibertyva requested changes
Will need to check auth-service.js against master's current auth to make sure changes from the okta consent fix make it to this branch.

2023-08-24 12:48 UTC, crolarlibertyva commented on auth.js
> +    if (argv.idp === "id.me" && !argv.seed) {
This isn't correct. The seed is only used when login.gov is the idp

2023-08-24 12:48 UTC, crolarlibertyva commented on totp-service.js
> +module.exports = { generateTOTP };
Let's double check the merge with master. totp.js was removed with the previous merges.

2023-08-24 13:19 UTC, dmekala-va commented on totp-service.js
> +module.exports = { generateTOTP };
totp.js wasn't removed it was just refactored as a script that developers could use with node to generate a token now:
https://github.com/department-of-veterans-affairs/lighthouse-auth-utils/blob/master/totp.js

2023-08-24 14:46 UTC, johnmweisz commented on totp-service.js
> +module.exports = { generateTOTP };
I don't think totp-service needs to exist, we are using the node module speakeasy directly in auth.js now.  The totp.js file still exists but only as a console app instead of an export.. If for some reason you need the generateTOTP function outside of the existing files we can discuss needs but it is preferable to leave totp related code as is.

2023-08-24 14:46 UTC, johnmweisz commented on totp.js
> +const { generateTOTP } = require("./totp-service.js");
There is no reason to reference a totp-service as this doesn't add anything that the node module speakeasy it uses already does.

2023-08-24 14:57 UTC, johnmweisz commented on auth-service.js
> +
speakeasy should be added here

2023-08-24 14:57 UTC, johnmweisz commented on auth-service.js
> +      const { generateTOTP } = require("./totp-service.js");
This should reference the speakeasy node module instead of the unnecessary totp-service.js file.

2023-08-24 14:57 UTC, johnmweisz commented on auth-service.js
> +      const totp = generateTOTP(args.seed);
This should reference the speakeasy node module instead of the unnecessary totp-service.js file.

2023-08-24 14:58 UTC, johnmweisz commented on auth-service.js
> +      const { generateTOTP } = require("./totp-service.js");
remove

2023-08-24 15:00 UTC, johnmweisz commented on totp.js
> +const { generateTOTP } = require("./totp-service.js");
This file should not need to change, it is no longer being used by any auth related code.

2023-09-12 20:43 UTC, johnmweisz approved these changes

2023-09-12 20:44 UTC, johnmweisz commented
would like a second approval as well

2023-09-15 00:51 UTC, dbrown-va approved these changes

2023-09-15 17:17 UTC, merged