API-29630 add wsEndpoint option and slim dockerfile
department-of-veterans-affairs/lighthouse-auth-utils pull request #76
Opened 2023-09-08 18:19 UTC by johnmweisz

- simplifies docker file
- adds wsEndpoint option so that docker can connect to chrome debug on Macs

2023-09-15 20:27 UTC, crolarlibertyva commented on Dockerfile
> -
Confirmed in my amd64 testing.
```
Error: Failed to launch the browser process!
/home/node/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:300:20)
    at Interface.<anonymous> (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:288:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    ```

2023-09-15 20:28 UTC, crolarlibertyva requested changes
Chrome dependencies are still needed for vanilla non-mac docker runs.

2023-09-18 16:24 UTC, johnmweisz commented on Dockerfile
> -
this download doesn't work for me, I needed to remove it to get docker to build.

2023-09-18 16:26 UTC, johnmweisz commented on Dockerfile
> -
I will add it back but I don't think this is an optimal solution

2023-09-18 16:30 UTC, johnmweisz commented on Dockerfile
> -
this suggests an alternative, how can I reproduce this error? https://stackoverflow.com/questions/66214552/tmp-chromium-error-while-loading-shared-libraries-libnss3-so-cannot-open-sha

2023-09-18 16:38 UTC, crolarlibertyva commented on Dockerfile
> -
Yeah, give that a try. We only need the dependencies. Might as well be direct about it.

2023-09-18 20:00 UTC, johnmweisz commented on Dockerfile
> -
reverting this and marking resolved, will review dockerfile changes at another time.

2023-09-18 20:31 UTC, crolarlibertyva approved these changes

2023-09-18 20:32 UTC, merged